### PR TITLE
Add TypeScript declarations

### PR DESCRIPTION
**Pull request by cspotcode**
Replaces #147, per https://github.com/amwmedia/plop/pull/147#issuecomment-509387167

Subject to change; blocked by amwmedia/node-plop#111.

### CODE REVIEW

**Comment by crutchcorn** [comment]
Curious, why not export * from node-plop? Additionally, why is it under plop.d.ts and not index.d.ts?

**Comment by crutchcorn** [comment]
Also, pinging @feimosi and @tannerntannern  

Closing other PR

**Comment by cspotcode** [comment]
@crutchcorn 

> Curious, why not export * from node-plop?

I figure `require('plop')` isn't necessarily going to always export everything from `require('node-plop')`.  If `node-plop` adds a function to its API -- `import {showHelpText} from 'node-plop';` -- but that function cannot be accessed via `import {showHelpText} from 'plop';` -- then we can't `export *`.

If we want to wildcard export all types and interfaces without the danger of erroneously exporting values, we can split the node-plop types out.  So we can `export * from 'node-plop/types';`

> Additionally, why is it under plop.d.ts and not index.d.ts?

This more closely matches reality and the output of the TypeScript compiler.  We are describing the interface of `lib/plop.js`, so the file is `lib/plop.d.ts`.  package.json says `"main": "lib/plop"` which handles resolution both for node at runtime and TypeScript at compile-time.

**Comment by amwmedia** [comment]
I know there were some discussions around how the types should be exposed. Is this PR ready to be merged?

**Pull request merged**
