### PR TITLE
Update typescript example

### PR DESCRIPTION
**Pull request by FDiskas**
closes https://github.com/plopjs/plop/issues/192

Make sure you have installed `ts-node` befor using it.

### CODE REVIEW

**Comment by FDiskas** [comment]
I deleted plopfile.js it is not needed. plopjs tries ts-node without any additional configuration or compilation. ts-node parses ts files on the fly so plopjs understands it out of the box.

**Comment by ivanoats** [comment]
Is it possible to review the README with only the sections you modified? It would be easier to review if it didn't modify the whole file.

**Comment by FDiskas** [comment]
I'm sorry,
I added section from line 608. At the very bottom.

**Comment by crutchcorn** [comment]
Ahh @FDiskas that's probably my bad. I didn't realize the autoformatter ran on the README. Don't worry about it, I can fix the diffing when I'm ready to review (just started vacation w/ a 14 hr drive. Will try to review in the next few days from my laptop)

**Comment by FDiskas** [comment]
Thank you. Drive safe and come back alive :)
Lucky "bastard" :) I already forgot how vacation looks like :D

**Comment by crutchcorn** [comment]
Just as a heads up @FDiskas - I'm releasing `plop@3` really really soon (this weekend at the latest). It inherently changes how `examples` are listed (they're now tied to tests). 

This won't make it into that initial merge, but the good news is that we can now not only have an example for TS usage, but include it in our tests!

I'll be taking this PR post-3 launch and turning it into a test. Huge thanks for the PR! I'll make sure to cherry-pick to give proper credit in commit history :)

**Comment by crutchcorn** [comment]
Closing, since we now have a properly documented TS example usage here: https://github.com/plopjs/plop/tree/main/packages/plop/tests/examples/typescript

**Pull request closed without merging**
