### PR TITLE
build: exporting assets and separating bin file

### PR DESCRIPTION
**Pull request by shubhamzanwar**
- Export Plop and run function from the `./src/plop.js`
- Separate the bin folder to `./bin/plop.js`

### CODE REVIEW

**Comment by amwmedia** [comment]
interesting, what are the main benefits that you see for this restructuring?

**Comment by shubhamzanwar** [comment]
@amwmedia I am trying to create a module that delivers a feature but also has the ability to auto generate code for that feature. I'm using plop for the auto generation part. i want the ability to modify the arguments to `Plop.launch` in my module's JS code. Hence, I am exporting `Plop` from `src/plop.js`. To make sure that the functioning of this library itself isn't affected, I created a separate `bin/plop.js` that would be exposed as the `bin` in `package.json`

Hope that made sense :)

**Comment by amwmedia** [comment]
yeah, I like it. Should make it much easier to create CLI tools that use Plop under the hood.

**Comment by shubhamzanwar** [comment]
Yes! That's exactly what I was going for :)

**Comment by shubhamzanwar** [comment]
@amwmedia can we merge this?

**Comment by amwmedia** [comment]
Sorry, I've been pretty busy with other things. I will get to this, hopefully soon

**Pull request merged**
